---
- name: Restart dnclient
  command:
    cmd: /opt/defined/dnclient stop && /opt/defined/dnclient start
  when: "'dnclient.service' in ansible_facts.services and ansible_facts.services['dnclient.service'].state == 'running'"
  listen: "restart dnclient"

- name: Start dnclient
  command:
    cmd: /opt/defined/dnclient start
  when: "'dnclient.service' in ansible_facts.services and ansible_facts.services['dnclient.service'].state != 'running'"
  listen: "restart dnclient"
